services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - ipvlan_escape
      - default
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  ipvlan_escape:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l3
