services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - bridge_escape
      - host_escape
      - default

networks:
  bridge_escape:
    driver: macvlan
    driver_opts:
      parent: docker0
  host_escape:
    driver: ipvlan
    driver_opts:
      parent: eth0
      ipvlan_mode: l3
